# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        #setup special, global autowiring rules
        bind:
            $uploadPath: '%kernel.project_dir%/public/uploads'
            $shapePath: '%kernel.project_dir%/public/shp'
            $xsdPath: '%kernel.project_dir%/public/uploads/xsd/2_5463337664826573801.xsd'
            $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\MailerSender:
        arguments:
            $user: '%env(MAILER_USER)%'
            $password: '%env(MAILER_PASSWORD)%'

    App\Service\ApiClient\EServicesClient:
        arguments:
            $baseUri: '%env(ES_API_TOKEN)%'
        calls:
            - method: setAccessToken
              arguments:
                  $clientId: '%env(ES_API_CLIENT_ID)%'
                  $clientSecret: '%env(ES_API_CLIENT_SECRET)%'

